[package]
name = "yuko"
version = "0.1.1"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html
[lib]
name = "yuko"
crate-type = ["cdylib"]

[dependencies]
pyo3 = "0.22.4"
regex = "1.11.0"
